-- Import PADRON_MONOTRIBUTO_completo_v2.csv (428 filas) contra la base real.
-- Validado antes de generar esto: 347/349 coinciden EXACTO con la fórmula por
-- componentes (calcularCuotaComponentes, ver commit "fórmula por componentes"),
-- 1 excepción real (socio 130, actividad ventas en vez de locaciones — se
-- marca cur_manual) resuelta explícitamente abajo, 0 errores de parseo.
-- 349 actualizaciones (ya existían en monotributos) + 79 altas nuevas
-- (76 con nombre real de Legajos, 3 "ingresante 01/09" sin legajo cargado
-- todavía — marcados con nombre placeholder para que RRHH los complete).

BEGIN;

update public.monotributos set categoria='C', condicion='no_aportante', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365298'; -- socio 2
update public.monotributos set categoria='C', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365897'; -- socio 22
update public.monotributos set categoria='D', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365548'; -- socio 38
update public.monotributos set categoria='B', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365376'; -- socio 43
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=1, estado='ACTIVO', updated_at=now() where id_local='292365240'; -- socio 46
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365446'; -- socio 55
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365280'; -- socio 95
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365645'; -- socio 98
update public.monotributos set categoria='H', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365315'; -- socio 107
update public.monotributos set categoria='B', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365228'; -- socio 113
update public.monotributos set categoria='B', condicion='comun', zona='provincia', iibb_aporta=true, adherentes_cantidad=2, estado='ACTIVO', updated_at=now(), cur_manual = true, cur = 124043.17 where id_local='292365740'; -- socio 130: actividad ventas (no locaciones) según credencial real, la fórmula por componentes (solo locaciones) no le pega — override explícito
update public.monotributos set categoria='B', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365368'; -- socio 183
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=1, estado='ACTIVO', updated_at=now() where id_local='292365888'; -- socio 212
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365420'; -- socio 226
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365575'; -- socio 278
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365304'; -- socio 290
update public.monotributos set categoria='B', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365431'; -- socio 297
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365612'; -- socio 319
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365448'; -- socio 343
update public.monotributos set categoria='C', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365709'; -- socio 356
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=2, estado='ACTIVO', updated_at=now() where id_local='292365192'; -- socio 365
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=1, estado='ACTIVO', updated_at=now() where id_local='292365344'; -- socio 389
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365532'; -- socio 396
update public.monotributos set categoria='B', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365242'; -- socio 455
update public.monotributos set categoria='B', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=1, estado='ACTIVO', updated_at=now() where id_local='292365147'; -- socio 521
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365181'; -- socio 594
update public.monotributos set categoria='F', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=1, estado='ACTIVO', updated_at=now() where id_local='292365824'; -- socio 690
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365924'; -- socio 709
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366047'; -- socio 829
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366051'; -- socio 837
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365250'; -- socio 882
update public.monotributos set categoria='C', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365382'; -- socio 1053
update public.monotributos set categoria='B', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=1, estado='ACTIVO', updated_at=now() where id_local='292365553'; -- socio 1181
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365295'; -- socio 1187
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365349'; -- socio 1334
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365601'; -- socio 1365
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366081'; -- socio 1402
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365749'; -- socio 1446
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365990'; -- socio 1547
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365839'; -- socio 1585
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365599'; -- socio 1611
update public.monotributos set categoria='B', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365629'; -- socio 1941
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365957'; -- socio 2023
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365741'; -- socio 2068
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365869'; -- socio 2119
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365393'; -- socio 2123
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=1, estado='ACTIVO', updated_at=now() where id_local='292366060'; -- socio 2147
update public.monotributos set categoria='B', condicion='jubilado', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365723'; -- socio 2212
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366092'; -- socio 2248
update public.monotributos set categoria='B', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365687'; -- socio 2253
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365993'; -- socio 2276
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365928'; -- socio 2414
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365124'; -- socio 2423
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=1, estado='ACTIVO', updated_at=now() where id_local='292365501'; -- socio 2459
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366007'; -- socio 2491
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365697'; -- socio 2557
update public.monotributos set categoria='B', condicion='jubilado', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365787'; -- socio 2565
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365648'; -- socio 2584
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365633'; -- socio 2688
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365923'; -- socio 2713
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=1, estado='ACTIVO', updated_at=now() where id_local='292365598'; -- socio 2719
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365463'; -- socio 2758
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365178'; -- socio 2791
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=1, estado='ACTIVO', updated_at=now() where id_local='292365248'; -- socio 2854
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=1, estado='ACTIVO', updated_at=now() where id_local='292365710'; -- socio 2863
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365775'; -- socio 2899
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=3, estado='ACTIVO', updated_at=now() where id_local='292365302'; -- socio 2907
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365380'; -- socio 2955
update public.monotributos set categoria='B', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365480'; -- socio 2985
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365668'; -- socio 2994
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365825'; -- socio 3086
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365421'; -- socio 3092
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365694'; -- socio 3107
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365915'; -- socio 3144
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365764'; -- socio 3149
update public.monotributos set categoria='C', condicion='comun', zona='provincia', iibb_aporta=true, adherentes_cantidad=1, estado='ACTIVO', updated_at=now() where id_local='292365208'; -- socio 3153
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365827'; -- socio 3159
update public.monotributos set categoria='H', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365386'; -- socio 3163
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365247'; -- socio 3184
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=1, estado='ACTIVO', updated_at=now() where id_local='292365803'; -- socio 3188
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365189'; -- socio 3292
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365942'; -- socio 3309
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365998'; -- socio 3329
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366061'; -- socio 3345
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365861'; -- socio 3351
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365846'; -- socio 3359
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365111'; -- socio 3362
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365626'; -- socio 3401
update public.monotributos set categoria='C', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365989'; -- socio 3449
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365970'; -- socio 3470
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=true, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365206'; -- socio 3474
update public.monotributos set categoria='B', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365675'; -- socio 3477
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365588'; -- socio 3548
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=2, estado='ACTIVO', updated_at=now() where id_local='292365711'; -- socio 3571
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365627'; -- socio 3586
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365974'; -- socio 3710
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365142'; -- socio 3717
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365562'; -- socio 3719
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365378'; -- socio 3736
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365757'; -- socio 3737
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365301'; -- socio 3782
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365112'; -- socio 3806
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365818'; -- socio 3864
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366105'; -- socio 3968
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365791'; -- socio 3972
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365730'; -- socio 4052
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365458'; -- socio 4058
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365632'; -- socio 4073
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365407'; -- socio 4096
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365445'; -- socio 4100
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365780'; -- socio 4104
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365443'; -- socio 4129
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=1, estado='ACTIVO', updated_at=now() where id_local='292365541'; -- socio 4143
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365285'; -- socio 4146
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365951'; -- socio 4209
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365985'; -- socio 4215
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365647'; -- socio 4239
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365197'; -- socio 4260
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365643'; -- socio 4261
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365814'; -- socio 4279
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=1, estado='ACTIVO', updated_at=now() where id_local='292365543'; -- socio 4295
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365891'; -- socio 4329
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365110'; -- socio 4397
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365823'; -- socio 4457
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365173'; -- socio 4488
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365660'; -- socio 4512
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365122'; -- socio 4546
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365955'; -- socio 4562
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365762'; -- socio 4580
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366079'; -- socio 4642
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='INACTIVO', updated_at=now() where id_local='292365883'; -- socio 4707
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365312'; -- socio 4709
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365958'; -- socio 4721
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365416'; -- socio 4722
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366070'; -- socio 4731
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365973'; -- socio 4734
update public.monotributos set categoria='B', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365425'; -- socio 4736
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365341'; -- socio 4737
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=1, estado='ACTIVO', updated_at=now() where id_local='292365176'; -- socio 4783
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365701'; -- socio 4805
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365433'; -- socio 4816
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='INACTIVO', updated_at=now() where id_local='292365265'; -- socio 4874
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365834'; -- socio 4882
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365504'; -- socio 4894
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365581'; -- socio 4905
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365879'; -- socio 4921
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366093'; -- socio 4931
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365383'; -- socio 4947
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365159'; -- socio 4959
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365689'; -- socio 4969
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365774'; -- socio 4972
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365297'; -- socio 4976
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='capital', iibb_aporta=false, adherentes_cantidad=1, estado='ACTIVO', updated_at=now() where id_local='292365146'; -- socio 4979
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365486'; -- socio 4991
update public.monotributos set categoria='A', condicion='asociado_cooperativa', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365555'; -- socio 4997
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365514'; -- socio 5007
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=1, estado='ACTIVO', updated_at=now() where id_local='292365472'; -- socio 5011
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365867'; -- socio 5018
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365927'; -- socio 5023
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365282'; -- socio 5034
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366040'; -- socio 5058
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365781'; -- socio 5065
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365564'; -- socio 5075
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365704'; -- socio 5076
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365680'; -- socio 5078
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365395'; -- socio 5094
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365196'; -- socio 5098
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366046'; -- socio 5107
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=true, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365546'; -- socio 5108
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365215'; -- socio 5113
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365428'; -- socio 5115
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365896'; -- socio 5116
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365272'; -- socio 5121
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365976'; -- socio 5139
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='INACTIVO', updated_at=now() where id_local='292365817'; -- socio 5142
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365703'; -- socio 5147
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365138'; -- socio 5158
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='INACTIVO', updated_at=now() where id_local='292365517'; -- socio 5171
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365860'; -- socio 5176
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365485'; -- socio 5190
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365381'; -- socio 5198
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365440'; -- socio 5205
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366003'; -- socio 5215
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365293'; -- socio 5217
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=true, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365945'; -- socio 5224
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365309'; -- socio 5228
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366112'; -- socio 5229
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365435'; -- socio 5231
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365496'; -- socio 5232
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365732'; -- socio 5234
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365359'; -- socio 5236
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365145'; -- socio 5238
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365725'; -- socio 5241
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365403'; -- socio 5246
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365591'; -- socio 5248
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365257'; -- socio 5249
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366082'; -- socio 5251
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365219'; -- socio 5255
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365850'; -- socio 5259
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365218'; -- socio 5261
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365172'; -- socio 5262
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=1, estado='ACTIVO', updated_at=now() where id_local='292365855'; -- socio 5263
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366034'; -- socio 5265
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365838'; -- socio 5266
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365372'; -- socio 5269
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=1, estado='ACTIVO', updated_at=now() where id_local='292365515'; -- socio 5270
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365238'; -- socio 5271
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=1, estado='ACTIVO', updated_at=now() where id_local='292365570'; -- socio 5272
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365299'; -- socio 5276
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365592'; -- socio 5280
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365797'; -- socio 5281
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365390'; -- socio 5282
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='INACTIVO', updated_at=now() where id_local='292365799'; -- socio 5283
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365394'; -- socio 5284
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365658'; -- socio 5290
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365269'; -- socio 5291
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365281'; -- socio 5292
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365895'; -- socio 5293
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365793'; -- socio 5295
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365258'; -- socio 5298
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365717'; -- socio 5299
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365693'; -- socio 5301
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366096'; -- socio 5303
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365331'; -- socio 5308
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366055'; -- socio 5309
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365457'; -- socio 5315
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365487'; -- socio 5318
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365784'; -- socio 5323
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366114'; -- socio 5326
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=1, estado='ACTIVO', updated_at=now() where id_local='292365714'; -- socio 5328
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365417'; -- socio 5330
update public.monotributos set categoria='A', condicion='no_aportante', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365751'; -- socio 5335
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365373'; -- socio 5346
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365747'; -- socio 5351
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365452'; -- socio 5353
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='INACTIVO', updated_at=now() where id_local='292365745'; -- socio 5355
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365786'; -- socio 5356
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365288'; -- socio 5358
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=true, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365698'; -- socio 5360
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365489'; -- socio 5362
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=1, estado='ACTIVO', updated_at=now() where id_local='292365796'; -- socio 5363
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='INACTIVO', updated_at=now() where id_local='292365152'; -- socio 5366
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365606'; -- socio 5367
update public.monotributos set categoria='B', condicion='comun', zona='capital', iibb_aporta=true, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365337'; -- socio 5368
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365922'; -- socio 5371
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365836'; -- socio 5372
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365211'; -- socio 5373
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365864'; -- socio 5374
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365743'; -- socio 5376
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365210'; -- socio 5377
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365347'; -- socio 5383
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366012'; -- socio 5384
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365306'; -- socio 5388
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365852'; -- socio 5390
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365830'; -- socio 5391
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365969'; -- socio 5395
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365249'; -- socio 5397
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365870'; -- socio 5398
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365439'; -- socio 5399
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365904'; -- socio 5401
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365859'; -- socio 5402
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365979'; -- socio 5405
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365673'; -- socio 5412
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365902'; -- socio 5417
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365476'; -- socio 5428
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365552'; -- socio 5429
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365157'; -- socio 5434
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365885'; -- socio 5438
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366054'; -- socio 5439
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365691'; -- socio 5440
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365569'; -- socio 5443
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365679'; -- socio 5444
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365502'; -- socio 5445
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365624'; -- socio 5447
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='INACTIVO', updated_at=now() where id_local='292365350'; -- socio 5449
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365933'; -- socio 5451
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365914'; -- socio 5452
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365323'; -- socio 5453
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365769'; -- socio 5455
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365527'; -- socio 5456
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365761'; -- socio 5457
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365510'; -- socio 5462
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365204'; -- socio 5468
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365994'; -- socio 5470
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365600'; -- socio 5473
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365567'; -- socio 5479
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365866'; -- socio 5484
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365329'; -- socio 5485
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365671'; -- socio 5486
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365934'; -- socio 5488
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365409'; -- socio 5489
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='INACTIVO', updated_at=now() where id_local='292365556'; -- socio 5490
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='INACTIVO', updated_at=now() where id_local='292365595'; -- socio 5493
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='INACTIVO', updated_at=now() where id_local='292365956'; -- socio 5495
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365649'; -- socio 5497
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366018'; -- socio 5498
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365826'; -- socio 5500
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365739'; -- socio 5502
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366072'; -- socio 5503
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365634'; -- socio 5504
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366086'; -- socio 5505
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366083'; -- socio 5507
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365153'; -- socio 5510
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366077'; -- socio 5512
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365988'; -- socio 5514
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365961'; -- socio 5518
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365361'; -- socio 5519
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365137'; -- socio 5521
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365259'; -- socio 5522
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365565'; -- socio 5523
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365203'; -- socio 5525
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365447'; -- socio 5526
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366041'; -- socio 5529
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365221'; -- socio 5530
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365833'; -- socio 5531
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365886'; -- socio 5533
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365872'; -- socio 5534
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365829'; -- socio 5538
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365477'; -- socio 5541
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365987'; -- socio 5544
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365876'; -- socio 5545
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365801'; -- socio 5547
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365475'; -- socio 5548
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365678'; -- socio 5551
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365220'; -- socio 5554
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366011'; -- socio 5556
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365738'; -- socio 5557
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365971'; -- socio 5558
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366020'; -- socio 5559
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366035'; -- socio 5560
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365216'; -- socio 5564
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='INACTIVO', updated_at=now() where id_local='292365470'; -- socio 5565
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365744'; -- socio 5566
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365136'; -- socio 5567
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365179'; -- socio 5569
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365230'; -- socio 5570
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365168'; -- socio 5571
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365214'; -- socio 5572
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366107'; -- socio 5574
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365202'; -- socio 5576
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366073'; -- socio 5577
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366084'; -- socio 5578
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365561'; -- socio 5579
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292366078'; -- socio 5580
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365835'; -- socio 5583
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365639'; -- socio 5584
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365201'; -- socio 5585
update public.monotributos set categoria='A', condicion='comun', zona='capital', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365296'; -- socio 5586
update public.monotributos set categoria='A', condicion='comun', zona='provincia', iibb_aporta=false, adherentes_cantidad=0, estado='ACTIVO', updated_at=now() where id_local='292365614'; -- socio 5587

-- Altas nuevas (no existían en monotributos)
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD000140', 'Guillen Sacsa Natividad', '140', 'E', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD000300', 'Poncino Maximiliano Nahuel', '300', 'D', 'comun', 'capital', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD000341', 'Gonzalez Claudio Alberto', '341', 'C', 'comun', 'capital', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD000612', 'Irrazabal Romina Gisela', '612', 'A', 'asociado_cooperativa', 'provincia', false, 1, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD000788', 'Martinez Jose Luis', '788', 'C', 'comun', 'provincia', true, 0, 'ACTIVO', 'IIBB ARBA $29,260.00 · dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD000856', 'Ramirez Benitez Martina Concepcion', '856', 'B', 'comun', 'provincia', true, 0, 'ACTIVO', 'IIBB ARBA $18,720.00 · dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD001387', 'Maidana Matias Ezequiel', '1387', 'C', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD001486', 'Rojas Damian Rodrigo', '1486', 'A', 'asociado_cooperativa', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD001954', 'Ledesma Benitez Mario Dionel', '1954', 'A', 'asociado_cooperativa', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD002271', 'Bianchi Jorgelina', '2271', '', 'comun', 'provincia', false, 0, 'ACTIVO', 'SIN CREDENCIAL � dato planilla RRHH (validar cuando llegue)', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD002570', 'Puma Florencia Beatriz', '2570', 'A', 'asociado_cooperativa', 'capital', false, 1, 'ACTIVO', 'dato de credencial F.1520 · �  REVISAR: planilla $75,221.73 �  credencial $69,635.96', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD002764', 'Palavecino Jorge Luis', '2764', 'A', 'asociado_cooperativa', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD003141', 'Ramirez Gomez Luis', '3141', 'A', 'asociado_cooperativa', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD003180', 'Carballo Gisela Soledad', '3180', 'A', 'asociado_cooperativa', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD003255', 'Lampert Victor Julian', '3255', 'A', 'asociado_cooperativa', 'capital', false, 0, 'ACTIVO', 'dato de credencial F.1520 · �  REVISAR: planilla $75,221.73 �  credencial $43,941.41', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD003264', 'Rojas Elbio Hernan', '3264', 'A', 'asociado_cooperativa', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD003364', 'Torres Orlando Daniel', '3364', 'A', 'asociado_cooperativa', 'capital', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD003868', 'Alvarez Adriana Vanesa', '3868', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520 · �  REVISAR: planilla $43,941.41 �  credencial $49,527.18', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD004075', 'Luna Carlos Javier', '4075', 'A', 'asociado_cooperativa', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD004102', 'Jaime Daniel Alejandro', '4102', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520 · �  REVISAR: planilla $43,941.41 �  credencial $49,527.18', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD004103', 'Jaime Daniel Oscar', '4103', '', 'comun', 'provincia', false, 0, 'ACTIVO', 'SIN CREDENCIAL � dato planilla RRHH (validar cuando llegue)', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD004219', 'Trejo Fernando Adrian', '4219', 'A', 'asociado_cooperativa', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD004228', 'Cardoso Cordero Daiana Evelyn', '4228', 'A', 'asociado_cooperativa', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD004246', 'Subelza Ivana Carina', '4246', 'A', 'asociado_cooperativa', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD004519', 'Milich Gabriela Soledad', '4519', 'A', 'asociado_cooperativa', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD004561', 'Prezel Roberto Carlos', '4561', 'A', 'asociado_cooperativa', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD004563', 'Hernandez Zarate Ingrid Maricel', '4563', 'A', 'asociado_cooperativa', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD004577', 'Pereyra Brenda Camila', '4577', 'A', 'asociado_cooperativa', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD004788', 'Monzon Myriam Elizabeth', '4788', 'A', 'asociado_cooperativa', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD004968', 'Torres Maria Soledad', '4968', 'A', 'asociado_cooperativa', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005014', 'Moreno Alejandro Ezequiel', '5014', 'A', 'asociado_cooperativa', 'capital', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005020', 'Camino Jorge Andres', '5020', 'A', 'comun', 'capital', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005099', 'Campos Alejandra Patricia', '5099', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005105', 'Cardozo Rocio Victoria', '5105', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005185', 'Santos Lucero Leila Yazmin', '5185', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005208', 'Virjan Micaela Ayelen', '5208', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005211', 'Ayala Laura Veronica', '5211', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005216', 'Torres Arce Agustina Gisela', '5216', 'A', 'comun', 'capital', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005221', 'Montoya Santiago Gabriel', '5221', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005237', 'Correa Joaquin Nazareno', '5237', 'A', 'comun', 'capital', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005244', 'Almiron Esteban Ezequiel', '5244', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005254', 'Frey Leonardo Ezequiel', '5254', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005274', 'Rosales Hector Daniel', '5274', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005288', 'Rojas Evelyn Natalia', '5288', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005327', 'Flores Estefania Elizabeth', '5327', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005329', 'Soler Ornela Paola', '5329', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005331', 'Firpo Natalia Soledad', '5331', 'A', 'comun', 'provincia', false, 0, 'INACTIVO', 'SIN CREDENCIAL � dato planilla RRHH (validar cuando llegue)', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005375', 'Sanabria Romina Anabela', '5375', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005379', 'Bustamante Soledad Lorena', '5379', 'A', 'comun', 'provincia', false, 1, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005381', 'Alfonso Joel Adrian', '5381', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005392', 'Aredes Alberto Martin', '5392', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005400', 'Iñigo Marcelo Daniel', '5400', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005407', 'Hipolito Myriam Noemi', '5407', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005408', 'Elicabe Polo', '5408', 'A', 'comun', 'capital', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005416', 'Mendieta Gilda Talia', '5416', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'SIN CREDENCIAL � dato planilla RRHH (validar cuando llegue)', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005464', 'Quiñonez Silvia', '5464', 'A', 'comun', 'capital', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005467', 'Lopez Silvana Cecilia', '5467', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005477', 'Gomez Florencia Rocio', '5477', 'A', 'comun', 'capital', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005499', 'Vera Nicolas Zacarias', '5499', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'SIN CREDENCIAL � dato planilla RRHH (validar cuando llegue)', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005508', 'Salahub Barbara Florencia', '5508', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005509', 'Vallard Alexis Nicolas', '5509', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005511', 'Santillan Gaston Ezequiel', '5511', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005513', 'Verdun Juan Emanuel', '5513', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005516', 'Lopez Laureano Milker', '5516', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005524', 'Nieto Castellanos Maite Lorena', '5524', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005528', 'Mongelo Brisa Ailen', '5528', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005537', 'Maldonado Claudio Leonardo', '5537', 'A', 'comun', 'provincia', false, 0, 'INACTIVO', 'SIN CREDENCIAL � dato planilla RRHH (validar cuando llegue)', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005542', 'Ledesma Gonzalez Santiago Adair', '5542', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'SIN CREDENCIAL � dato planilla RRHH (validar cuando llegue)', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005546', 'Quispe Serrano Silvia Patricia', '5546', 'A', 'comun', 'capital', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005550', 'Gramajo Mercedes Noemi', '5550', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005555', 'Sosa Delvalle Sasha Liz', '5555', 'A', 'comun', 'capital', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005561', 'Navarrete Adrian Osvaldo', '5561', 'A', 'comun', 'capital', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005563', 'De Oliveira Assuncao Joao Vitor', '5563', 'A', 'comun', 'capital', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005568', 'Gonzalez Mirta Angelica', '5568', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005573', 'Quintana Marcelo Esteban', '5573', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'SIN CREDENCIAL � dato planilla RRHH (validar cuando llegue)', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005575', 'Lezcano Esteban German', '5575', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'dato de credencial F.1520', current_date) on conflict (id_local) do nothing;
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005581', 'SOCIO 5581 (sin legajo encontrado)', '5581', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'ingresante 01/09 · dato de credencial F.1520', current_date) on conflict (id_local) do nothing; -- ⚠ sin legajo encontrado, nombre placeholder
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005582', 'SOCIO 5582 (sin legajo encontrado)', '5582', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'ingresante 01/09 · dato de credencial F.1520', current_date) on conflict (id_local) do nothing; -- ⚠ sin legajo encontrado, nombre placeholder
insert into public.monotributos (id_local, nombre, nro_socio, categoria, condicion, zona, iibb_aporta, adherentes_cantidad, estado, obs, fecha_alta) values ('PAD005588', 'SOCIO 5588 (sin legajo encontrado)', '5588', 'A', 'comun', 'provincia', false, 0, 'ACTIVO', 'ingresante 01/09 · dato de credencial F.1520', current_date) on conflict (id_local) do nothing; -- ⚠ sin legajo encontrado, nombre placeholder

COMMIT;
